<a href="https://colab.research.google.com/github/balinenisreedharnaidu/Data-Science-and-Machine-Learning/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myList=[1,2,3]
myList

[1, 2, 3]

In [ ]:
npArr=np.array(myList);
npArr
type(npArr)

numpy.ndarray

In [ ]:
myMat=[[1,2,3],[4,5,6]]
myMat

[[1, 2, 3], [4, 5, 6]]

In [ ]:
npMat=np.array(myMat)
npMat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5)) # 5 rows 5 columns in tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,10) # (start,stop,how many numbers to include) evenly spaced numbers
#0 and 5 also include

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(5) #identity matrix in linear alebra

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(1) #between 0 and 1

array([0.55274071])

In [ ]:
np.random.rand(5,2)

array([[0.51976717, 0.97284352],
       [0.6200303 , 0.50017368],
       [0.3119264 , 0.00264756],
       [0.34309629, 0.17214267],
       [0.2760671 , 0.27163295]])

In [ ]:
np.random.randn(10)  #standard normal distribution

array([ 7.65091920e-02, -1.18196222e-01,  4.05121521e-01, -2.42613798e-01,
       -5.41091867e-01,  1.21800111e+00,  1.94601687e-01,  1.20271682e-03,
       -1.56210574e+00,  2.41855544e-01])

In [ ]:
np.random.randn(2,3)

array([[-0.35183711, -0.28815526, -1.64379912],
       [ 0.23826933,  0.20302548, -0.4448029 ]])

In [ ]:
np.random.randint(0,101,25)


array([67, 83,  1, 67, 34, 53, 96,  4, 10, 73, 50, 68, 98, 67, 15, 46,  3,
       78,  9, 19, 99, 81, 86, 85, 53])

In [ ]:
np.random.randint(0,25,(5,5)) # take 5,5 matrix from randomly take element btwn 0 and 101

array([[ 6, 23,  0,  9, 16],
       [18,  3, 10, 16,  5],
       [ 6, 10,  6, 22,  8],
       [ 7, 13, 19, 22, 23],
       [ 6,  2,  0,  2,  2]])

In [ ]:
np.random.seed(42) #test below cell and this cell results u know what seed do
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr=np.random.randint(0,101,10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [ ]:
ranarr.max()
ranarr.min()

2

In [ ]:
ranarr.argmax() #index of max

5

In [ ]:
ranarr.argmin() #index of min

7

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
arr.shape

(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr=arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

---**Indexing and Selection**


In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[1:8:2] # [start index:end index :step index]

array([1, 3, 5, 7])

In [ ]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr[:]=101 #broadcast operations
arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [ ]:
arr2D=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr2D.shape

(3, 3)

In [ ]:
arr2D[1,1] # row1 col1 element

25

In [ ]:
arr2D[1][1]

25

In [ ]:
arr2D[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr2D[:2,1:] #select 2 rows and select elements from 1st element in each row
# start empty:end specify -- select from start and select no of rows/columns that end specify
# start specofy:end empty -- select from end and select no of rows/columns that start specify

array([[10, 15],
       [25, 30]])

In [ ]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr2D[2,2]# 2nd row 2nd indexed element
arr2D[0:5]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#broadcast a condition
arr2D>30

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [ ]:
arr==101

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
boolArr=arr2D>25
boolArr

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
arr2D[boolArr]

array([30, 35, 40, 45])

In [ ]:
arr2D

In [ ]:
arr2D[arr2D>25]

array([30, 35, 40, 45])

**numpy operations**

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2=arr+5 
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr+arr2 #add every number in 2 arrays

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
arr-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.var() #variance

8.25

In [ ]:
arr.std() #standard deviation

In [ ]:
arr=np.arange(0,25).reshape(5,5)

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis=0) #sum of each column

In [ ]:
arr.sum(axis=1) #sum across rowsnb